import type { ResourceType } from '@/types'

export interface ResourceTypeMeta {
  type:     ResourceType
  title:    string
  subtitle: string
  accent:   string
  cssVar:   string
  icon:     string
}

export const RESOURCE_TYPES: ResourceTypeMeta[] = [
  {
    type: 'lesson_plan',
    title: 'Lesson Plan',
    subtitle: 'Starter \u2192 main \u2192 plenary with differentiation',
    accent: 'amber',
    cssVar: '--amber',
    icon: 'lesson',
  },
  {
    type: 'worksheet',
    title: 'Worksheet',
    subtitle: 'Tiered tasks, extension, and answer key',
    accent: 'green',
    cssVar: '--green',
    icon: 'worksheet',
  },
  {
    type: 'quiz',
    title: 'Quiz',
    subtitle: 'Recall \u2192 apply \u2192 extended with mark scheme',
    accent: 'gold',
    cssVar: '--gold',
    icon: 'quiz',
  },
  {
    type: 'parent_email',
    title: 'Parent Email',
    subtitle: 'Professional, warm, under 250 words',
    accent: 'blue',
    cssVar: '--blue',
    icon: 'email',
  },
  {
    type: 'image',
    title: 'Image',
    subtitle: 'Educational illustration generated by AI',
    accent: 'amber',
    cssVar: '--amber',
    icon: 'image',
  },
  {
    type: 'presentation',
    title: 'Presentation',
    subtitle: 'Slide deck built and themed automatically',
    accent: 'green',
    cssVar: '--green',
    icon: 'presentation',
  },
]

export function metaFor(type: ResourceType): ResourceTypeMeta {
  return RESOURCE_TYPES.find((r) => r.type === type)!
}
